Repository ropensci/roweb3, pull requests merged in 2025-02, with the labels that each got.

#916 Translation Spanish Software Peer Review
  content/software-review/_index.es.md
  data/en/resources/softwarereview.json
  data/es/resources/softwarereview.json
  themes/ropensci/i18n/en.toml
  themes/ropensci/i18n/es.toml
  themes/ropensci/layouts/software-review/list.html
Labels: translation :mate:, ro-hackathon-2025

#959 Fixes on Spanish pages
  content/blog/2017-09-01-nsf-softwarereview/index.es.md
  content/blog/2021-07-27-censo2017/index.es.md
  content/blog/2022-04-19-software-review-editorial-challenges/index.es.md
  content/blog/2022-10-19-censo2017-one-year-after/index.es.md
  content/blog/2023-01-12-multilingual-publishing/index.es.md
  content/blog/2023-02-21-champions-kick-off/index.es.md
  content/blog/2023-02-27-runiverse-discovering/index.es.md
  content/blog/2023-03-30-r-universe-stars-3/index.es.md
  content/blog/2023-06-06-r-universe-stars-4/index.es.md
  content/blog/2023-06-09-communication/index.es.md
  content/blog/2023-09-15-r-universe-stars-5/index.es.md
  content/blog/2023-11-06-r-universe-interviews/index.es.md
  content/blog/2024-03-11-devguide-release-0.9.0/index.es.md
  content/blog/2024-07-09-multilingual-documentation-in-r/index.es.md
  content/blog/2024-10-10-czi-latam-grant/index.es.md
  content/blog/2024-12-03-r-universe-r-consortium-tlp/index.es.md
  content/blog/2024-12-17-localization-guide/index.es.md
  content/commcalls/2023-11-23/index.es.md
  content/technotes/_index.es.md
  data/team/champions.json
  data/team/mentors.json
  themes/ropensci/layouts/technotes/list.html
Labels: translation :mate:

#908 make community more markdown-based
  content/community/_index.es.md
  themes/ropensci/assets/_snippets/commcalls.en.md
  themes/ropensci/assets/_snippets/commcalls.es.md
  themes/ropensci/i18n/en.toml
  themes/ropensci/i18n/es.toml
  themes/ropensci/i18n/fr.toml
  themes/ropensci/layouts/community/list.html
Labels: enhancement, translation :mate:

#966 translate brands
  themes/ropensci/layouts/_default/index.html
  themes/ropensci/layouts/_default/single.html
  themes/ropensci/layouts/about/list.html
  themes/ropensci/layouts/blog/list.html
  themes/ropensci/layouts/careers/list.html
  themes/ropensci/layouts/champions/list.html
  themes/ropensci/layouts/commcalls/list.html
  themes/ropensci/layouts/community/list.html
  themes/ropensci/layouts/contact/list.html
  themes/ropensci/layouts/coworking/list.html
  themes/ropensci/layouts/donate/list.html
  themes/ropensci/layouts/events/single.html
  themes/ropensci/layouts/multilingual-publishing/list.html
  themes/ropensci/layouts/news/list.html
  themes/ropensci/layouts/packages/list.html
  themes/ropensci/layouts/papers/list.html
  themes/ropensci/layouts/partials/whole-page-fragments/brands.en.html
  themes/ropensci/layouts/partials/whole-page-fragments/brands.es.html
  themes/ropensci/layouts/r-universe/list.html
  themes/ropensci/layouts/resources/list.html
  themes/ropensci/layouts/software-review/list.html
  themes/ropensci/layouts/talks-papers/list.html
  themes/ropensci/layouts/talks/list.html
  themes/ropensci/layouts/training/list.html
Labels: translation :mate:

#968 translate community fragment
  themes/ropensci/layouts/_default/index.html
  themes/ropensci/layouts/partials/whole-page-fragments/community.en.html
  themes/ropensci/layouts/partials/whole-page-fragments/community.es.html
Labels: translation :mate:

#967 translate volunteer fragment
  themes/ropensci/layouts/careers/list.html
  themes/ropensci/layouts/champions/list.html
  themes/ropensci/layouts/community/list.html
  themes/ropensci/layouts/help-wanted/list.html
  themes/ropensci/layouts/multilingual-publishing/list.html
  themes/ropensci/layouts/news/list.html
  themes/ropensci/layouts/packages/list.html
  themes/ropensci/layouts/partials/whole-page-fragments/volunteer.en.html
  themes/ropensci/layouts/partials/whole-page-fragments/volunteer.es.html
  themes/ropensci/layouts/r-universe/list.html
  themes/ropensci/layouts/software-review/list.html
Labels: translation :mate:

#964 translate ask fragment
  themes/ropensci/layouts/community/list.html
  themes/ropensci/layouts/papers/list.html
  themes/ropensci/layouts/partials/whole-page-fragments/ask.en.html
  themes/ropensci/layouts/partials/whole-page-fragments/ask.es.html
  themes/ropensci/layouts/resources/list.html
  themes/ropensci/layouts/talks-papers/list.html
  themes/ropensci/layouts/talks/list.html
  themes/ropensci/layouts/training/list.html
Labels: translation :mate:

#886 Add first draft for blog post on fork/upstream relationship
  content/author/hugo-gruson/_index.md
  content/author/ruby-krasnow/_index.md
  content/blog/2025-02-20-forks-upstream-relationship/index.md
Labels: blog post
